// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWP391.DAL.Entities;

public partial class CustomerOption
{
    public int CustomerOptionId { get; set; }

    public int UserId { get; set; }

    public int? MessageId { get; set; }

    public int? InboxId { get; set; }

    public int? OutboxId { get; set; }

    public string OptionValue { get; set; }
}